name: GitHub Metrics

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

          user: geovanarosamendes

          template: classic
          base: header, repositories

          plugin_languages: yes
          plugin_languages_details: bytes-size, percentage
          plugin_languages_limit: 8
